language: java

jdk:
  - oraclejdk8

sudo: false

install: mvn -DskipTests=true -Dbasepom.check.skip-all=true -B install
script: mvn -B verify

before_script:
  - "psql -c 'create database jdbi_test;' -U postgres"
