language: java

sudo: false

# No much sense in keeping jdbi artifacts cached
before_cache:
  rm -rf $HOME/.m2/repository/org/jdbi

cache:
  directories:
    - '$HOME/.m2/repository'

before_install:
    - cp src/build/travis-toolchains.xml ~/.m2/toolchains.xml
    - [ -z "$secure_files_key" ] && export PROFILES=toolchains,oracle || export PROFILES=toolchains
    - [ -z "$secure_files_key" ] && openssl aes-256-cbc -K $secure_files_key -iv $secure_files_iv -in src/build/travis-settings.xml.enc -out ~/.m2/settings.xml -d || true
    - [ -z "$secure_files_key" ] && openssl aes-256-cbc -K $secure_files_key -iv $secure_files_iv -in src/build/travis-settings-security.xml.enc -out ~/.m2/settings-security.xml -d || true

install: mvn -Ptoolchains,oracle -DskipTests=true -Dbasepom.check.skip-all=true -Dmaven.javadoc.skip=true -B install

matrix:
  include:
    - env:
        - TESTS=Y
      script: mvn -Dmaven.javadoc.skip=true -Dbasepom.check.skip-basic=true -Dbasepom.check.skip-findbugs=true -Dbasepom.check.skip-pmd=true -Dbasepom.check.skip-checkstyle=true -P $PROFILES -B verify
      jdk: oraclejdk8
    - env:
        - DOCUMENTATION=Y
      script: mvn -DskipTests=true -Dbasepom.check.skip-all=true -P $PROFILES -B verify
      jdk: oraclejdk8
    - env:
        - CODE_STYLE=Y
      script: mvn -DskipTests=true -Dmaven.javadoc.skip=true -P $PROFILES -B verify
      jdk: oraclejdk8
